name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: |
          if [ "${{ env.NEXT_SEMI_DISABLE_LINT }}" = "1" ]; then
            echo "Lint disabled for CI"; 
          else
            npm run lint --if-present
          fi

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/
            .next/static/
            .next/server/
